version: '3.7'
services:
    postgres:
        image: postgres:9.6
        env_file:
            - .env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    webserver:
        image: jdaarevalo/docker-airflow:0.1.0
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        env_file:
            - .env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./store_files:/usr/local/airflow/store_files
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
